RecipeManagementSystem_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Recipe_App.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Recipe_App/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', v.home, name='home'),
    path('recipe_search', v.Search, name='recipe_search'),
    path('category/<str:cat>', v.Category, name='category'),
    path('signup', v.Signup.as_view(), name='signup'),
    path('login', v.Login.as_view(), name='login'),
    path('signout', v.Signout, name='signout'),
    path('addrecipe', v.addrecipe, name='addrecipe'), 
    path('viewpage/<int:rid>', v.viewpage, name='viewpage'), 
    path('myrecipe', v.recipelist, name='myrecipe'),
    path('editpage/<int:id>/', v.editRecipe, name='editpage'), 
    path('deletepage/<int:id>/', v.deleteRecipe, name='deletepage'), 
]

Recipe_App/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField

# Create your models here.

class Recipe(models.Model):
    recipe_name = models.CharField(max_length=150, null=False)
    recipe_img = models.ImageField()
    description = HTMLField(max_length=400, null=False)
    ingredients = HTMLField(max_length=2000, null=False)
    instructions = HTMLField(max_length=2000, null=False)
    category = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.recipe_name
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    class Meta:
        db_table = 'Recipe'

Recipe_App/views.py
from django.db.models.base import Model as Model
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from Recipe_App.models import Recipe
from Recipe_App.form import SignupForm, LoginForm
from django.views.generic.edit import FormView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db.models import Q

# Create your views here.

def home(request):
    recipes = Recipe.objects.filter()
    recipeSort = set()
    for i in recipes:
        recipeSort.add(i.category)
    context = {'recipes' : recipes, 'recipeSort': recipeSort}
    return render(request, 'home.html', context)

def Search(request):
    if request.method == 'POST':
        search_query = request.POST.get('search')
        recipes = Recipe.objects.filter(Q(recipe_name__icontains=search_query) | Q(description__icontains=search_query))
        context = {'recipes': recipes, 'search_query': search_query}
        return render(request, 'home.html', context)
    else:
        recipes = Recipe.objects.all()
        context = {'recipes': recipes}
        return render(request, 'home.html', context)
    
def Category(request, cat):
    recipes = Recipe.objects.all()
    recipeSort = set()
    for i in recipes:
        recipeSort.add(i.category)
    
    filterd_recipe = Recipe.objects.filter(category=cat)
    context = {'recipes' : filterd_recipe
    , 'recipeSort': recipeSort}
    return render(request, 'home.html', context)

# Auth/User------------------------------------------------------------------------
class Signup(FormView):
    template_name = 'signup.html'
    form_class = SignupForm
    success_url = '/login'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    

from django.contrib.auth import authenticate, login
from django.views.generic import FormView

class Login(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = '/'
    
    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(self.request, username=username, password=password)
        
        if user is not None:
            login(self.request, user)
            self.request.session['uid'] = user.id 
            return super().form_valid(form)
        else:
            form.add_error(None, 'Invalid username or password')
            return self.form_invalid(form)
    
def Signout(request):
    logout(request)
    return redirect('/')

#Recipe------------------------------------------------------------------------------

from Recipe_App.form import RecipeForm

def addrecipe(request):
    if not request.user.is_authenticated:
        return redirect('login') 

    if request.method == 'POST':
        uid = request.user.id  
        recipe_name = request.POST.get('recipe_name')
        recipe_img = request.FILES.get('recipe_img')
        description = request.POST.get('description')
        ingredients = request.POST.get('ingredients')
        instructions = request.POST.get('instructions')
        category = request.POST.get('category')
        
        recipe = Recipe()
        recipe.recipe_name = recipe_name
        recipe.recipe_img = recipe_img
        recipe.description = description
        recipe.ingredients = ingredients
        recipe.instructions = instructions
        recipe.category = category
        recipe.user = User.objects.get(id=uid) 
        recipe.save()
        return redirect('/')
    else:
        f = RecipeForm()
        context = {'form': f}
        return render(request, 'recipe.html', context)


#ViewRecipe---------------------------------------------------------------------------

def viewpage(request, rid):
    recipes = get_object_or_404(Recipe, id = rid)
    context = {'recipes' : recipes}
    return render(request, 'viewpage.html', context)


#Myrecipe------------------------------------------------------------------------------

def recipelist(request):
    uid = request.session.get('uid')
    print(f"UID from session: {uid}")
    if uid:
        rlist = Recipe.objects.filter(user=uid)
        context = {'recipelist': rlist}
        return render(request, 'myrecipe.html', context)
    else:
        return redirect('/login') 
    
def editRecipe(request, id):
    recipe = Recipe.objects.get(id=id)
    if request.method == "POST":
        form = RecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            print(form.errors) 
            return HttpResponse("Form is not valid")

    else:
        form = RecipeForm(instance=recipe)
    
    context = {'form':form}
    return render(request, 'edit_recipe.html',context)

def deleteRecipe(request, id):
    recipe = Recipe.objects.get(id = id)
    recipe.delete()
    return redirect('/myrecipe')

Recipe_App/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <title>{% block title %}{% endblock %}</title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'base.css' %}" />
    {% block css %}{% endblock %}

    <!-- bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <!-- NAVBAR -->
    <nav class="nav-container">
      <header
        class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom m-3 p-0"
      >
        <div class="col-md-3 mb-2 mb-md-0">
          <a
            href="/"
            class="d-inline-flex link-body-emphasis text-decoration-none"
          >
            <img
              src="{% static 'assets/img/logo/logo-no-background.png' %}"
              alt="Logo"
              width="80"
              height="60"
            />
          </a>
        </div>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
          <li>
            <a href="/addrecipe" class="nav-link px-2 link-secondary"
              >Add Recipe</a
            >
          </li>
          {% if user.is_authenticated %}
          <li>
            <a href="#" class="nav-link px-2 link-secondary"
              >Welcome, <b style="color: rgb(234, 234, 115)">{{user}}</b></a
            >
          </li>

          <li>
            <a href="/myrecipe" class="nav-link px-2 link-secondary"
              >My Recipe</a
            >
          </li>
          {% endif %}
        </ul>

        <div class="col-md-3 text-end">
          {% if user.is_authenticated %}
          <a
            href="/signout"
            class="btn btn-outline-warning me-2"
            style="text-decoration: none; color: black"
            >Logout</a
          >
          {% else %}
          <a
            href="/login"
            class="btn btn-outline-warning me-2"
            style="text-decoration: none; color: black"
            >Login</a
          >
          <a
            href="/signup"
            class="btn btn-warning"
            style="text-decoration: none; color: black"
            >Sign-up</a
          >
          {% endif %}
        </div>
      </header>
    </nav>

    {% block content %}{% endblock %}

    <!-- FOOTER -->
    <div class="footer-container">
      <footer
        class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top p-0 mb-3 m-0"
      >
        <p class="col-md-4 mb-0 text-body-secondary">
          © 2024 SavoryScript, Inc
        </p>

        <a
          href="/"
          class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none"
        >
          <img
            src="{% static 'assets/img/logo/logo-no-background.png' %}"
            alt="Logo"
            width="80"
            height="60"
          />
        </a>

        <ul class="nav col-md-4 justify-content-end">
          <li class="nav-item">
            <a href="#" class="nav-link px-2 text-body-secondary">Home</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="/addrecipe" class="nav-link px-2 text-body-secondary"
              >Add Recipe</a
            >
          </li>

          <li class="nav-item">
            <a href="/signout" class="nav-link px-2 text-body-secondary"
              >Logout</a
            >
          </li>
          {% else %}
          <li class="nav-item">
            <a href="/login" class="nav-link px-2 text-body-secondary">Login</a>
          </li>
          <li class="nav-item">
            <a href="/signup" class="nav-link px-2 text-body-secondary"
              >Sign-up</a
            >
          </li>
          {% endif %}
        </ul>
      </footer>
    </div>

    <!-- JS -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

Recipe_App/templates/edit_recipe.html
{% extends 'base.html' %}{% load static %}{%block title%} MyRecipe
{%endblock%}{%block content%}

<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table">
      {{ form.as_table }}
    </table>
    <button type="submit">Save Changes</button>
  </form>
</div>

{% endblock %}

Recipe_App/templates/home.html
{% extends 'base.html' %}{% load static %}{%block title%} Home
{%endblock%}{%block content%}

<!-- HERO -->
<section id="hero">
  <div class="px-4 pt-5 my-5 text-center border-bottom p-0 mt-3">
    <div class="overflow-hidden" style="max-height: 30vh">
      <div class="container px-5">
        <img
          src="{% static 'assets/img/hero.jpg' %}"
          class="img-fluid border rounded-3 shadow-lg mb-5"
          alt="Example image"
          width="700"
          height="500"
          loading="lazy"
        />
      </div>
    </div>
    <h1 class="display-4 fw-bold text-body-emphasis">SavoryScript</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">
        Unleash your inner chef with our vast collection of mouth-watering
        recipes. Whether you're a seasoned cook or a kitchen newbie, find
        step-by-step guides, expert tips, and creative ideas to make every meal
        a memorable one. Explore, cook, and savor the joy of homemade dishes
        today!
      </p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
        <form action="{% url 'recipe_search' %}" method="post">
          {% csrf_token %}
          <input
            type="text"
            name="search"
            style="padding: 0.5rem 5rem; border-radius: 1rem"
          />
          <button
            type="submit"
            value="search"
            class="btn btn-warning btn-lg px-4 me-sm-3"
          >
            Search Recipe
          </button>
        </form>
        <div class="btn-group">
          <button
            type="button"
            class="btn btn-outline-secondary btn-lg px-4 dropdown-toggle"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Category
          </button>
          <ul class="dropdown-menu">
            <li>
              <a
                class="dropdown-item {% if not current_category %}active{% endif %}"
                href="{% url 'home' %}"
                >All</a
              >
            </li>
            {% for category in recipeSort %}
            <li>
              <a
                class="dropdown-item {% if category == current_category %}active{% endif %}"
                href="{% url 'category' category %}"
              >
                {{ category }}
              </a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- CARD -->
<section id="card" class="container">
  <div class="row">
    {% for recipe in recipes %}
    <div class="col-sm-12 col-md-6 col-lg-4 mb-3 d-flex align-items-stretch">
      <div class="card" style="width: 18rem">
        <img
          src="{{ recipe.recipe_img.url }}"
          class="card-img-top"
          alt="recipe-img"
        />
        <div class="card-body d-flex flex-column">
          <h5 class="card-title">{{ recipe.recipe_name }}</h5>
          <p class="card-text">{{ recipe.description }}</p>
          <a href="/viewpage/{{ recipe.id }}" class="btn btn-warning mt-auto"
            >View</a
          >
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>

{%endblock%} {% block css %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}

Recipe_App/templates/login.html
{% extends 'base.html' %}{% load static %}{%block title%} Login
{%endblock%}{%block content%}

<form action="" method="post">
  {% csrf_token %}
  <table class="table">
    {{form.as_table}}
  </table>
  <div class="button m-3">
    <input class="btn btn-warning" type="submit" value="Login" />
  </div>

  <p class="m-3">Don't have a account? <a href="signup">Signup</a></p>
</form>

{%endblock%}

Recipe_App/templates/myrecipe.html
{% extends 'base.html' %}{% load static %}{%block title%} MyRecipe
{%endblock%}{%block content%}

<div class="container">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mb-3">
      {% if recipelist %} {% for r in recipelist %}
      <div class="col">
        <div class="card shadow-sm h-100">
          <div class="card-img-container">
            {% if r.recipe_img.url %}
            <img
              class="card-img-top"
              src="{{ r.recipe_img.url }}"
              alt="Thumbnail"
              style="object-fit: cover; height: 225px"
            />
            {% else %}
            <div class="placeholder-img">Thumbnail</div>
            {% endif %}
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ r.recipe_name }}</h5>
            <p class="card-text">{{ r.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a
                  href="/viewpage/{{ r.id }}"
                  class="btn btn-sm btn-outline-secondary"
                  >View</a
                >
                <a
                  href="/editpage/{{ r.id }}"
                  class="btn btn-sm btn-outline-secondary"
                  >Edit</a
                >
              </div>
              <small class="text-body-secondary">
                <a href="/deletepage/{{ r.id }}" class="text-danger">Delete</a>
              </small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <div class="col">
        <p>No recipes found.</p>
      </div>
      {% endif %}
    </div>
  </form>
</div>

{% endblock %}

Recipe_App/templates/recipe.html
{% extends 'base.html' %}{% load static %}{%block title%} Recipe
{%endblock%}{%block content%}

<div class="container">
  <h1 class="my-4">Add a New Recipe</h1>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table table-bordered">
      <tr>
        <th><label for="id_recipe_name">Recipe Name:</label></th>
        <td>
          <input
            type="text"
            name="recipe_name"
            maxlength="100"
            required
            id="id_recipe_name"
            class="form-control"
          />
        </td>
      </tr>
      <tr>
        <th><label for="id_recipe_img">Recipe Image:</label></th>
        <td>
          <input
            type="file"
            name="recipe_img"
            required
            id="id_recipe_img"
            class="form-control"
          />
        </td>
      </tr>
      <tr>
        <th><label for="id_description">Description:</label></th>
        <td>
          <textarea
            name="description"
            cols="40"
            rows="10"
            maxlength="500"
            required
            id="id_description"
            class="form-control"
          ></textarea>
        </td>
      </tr>
      <tr>
        <th><label for="id_ingredients">Ingredients:</label></th>
        <td>
          <textarea
            name="ingredients"
            cols="40"
            rows="10"
            maxlength="500"
            required
            id="id_ingredients"
            class="form-control"
          ></textarea>
        </td>
      </tr>
      <tr>
        <th><label for="id_instructions">Instructions:</label></th>
        <td>
          <textarea
            name="instructions"
            cols="40"
            rows="10"
            maxlength="500"
            required
            id="id_instructions"
            class="form-control"
          ></textarea>
        </td>
      </tr>
      <tr>
        <th><label for="id_category">Category:</label></th>
        <td>
          <input
            type="text"
            name="category"
            maxlength="100"
            required
            id="id_category"
            class="form-control"
          />
        </td>
      </tr>
      <tr>
        <th><label for="id_User">User:</label></th>
        <td>
          <input
            type="text"
            name="user"
            value="{{user}}"
            class="form-control"
          />
        </td>
      </tr>
    </table>
    <br />
    <div>
      <button type="submit" class="btn btn-warning">SAVE</button>
      <button type="reset" class="btn btn-secondary">RESET</button>
    </div>
  </form>
</div>

{% endblock %}

Recipe_App/templates/signup.html
{% extends 'base.html' %}{% load static %}{%block title%} Signup
{%endblock%}{%block content%}

<h1 class="text-center">Signup</h1>

<form action="" method="post">
  {% csrf_token %}
  <table class="table">
    <tr>
      <th>{{form.first_name.label_tag}}</th>
      <td>{{form.first_name}}</td>
    </tr>
    <tr>
      <th>{{form.last_name.label_tag}}</th>
      <td>{{form.last_name}}</td>
    </tr>
    <tr>
      <th>{{form.username.label_tag}}</th>
      <td>{{form.username}}</td>
    </tr>
    <tr>
      <th>{{form.email.label_tag}}</th>
      <td>{{form.email}}</td>
    </tr>
    <tr>
      <th>{{form.password1.label_tag}}</th>
      <td>{{form.password1}}</td>
    </tr>
    <tr>
      <th>{{form.password2.label_tag}}</th>
      <td>{{form.password2}}</td>
    </tr>
  </table>

  <div class="button m-3">
    <input class="btn btn-warning" type="submit" value="Signup" />
  </div>

  <p class="m-3">Already have a account? <a href="login">Login</a></p>
</form>

{%endblock%}

Recipe_App/templates/viewpage.html
{% extends 'base.html' %}{% load static %}{%block title%} viewrecipe
{%endblock%}{%block content%}

<div class="container-fluid p-0">
  <div class="row g-0 min-vh-100">
    <div class="col-md-6 recipe-image-container">
      <img
        src="{{ recipes.recipe_img.url }}"
        class="recipe-image"
        alt="{{ recipes.recipe_name }}"
      />
    </div>
    <div
      class="col-md-6 d-flex flex-column justify-content-center bg-dark text-warning p-4"
    >
      <h1 class="display-6 mb-2">{{ recipes.recipe_name }}</h1>
      <hr class="my-4" />
      <h3 class="h4 mb-3">Ingredients</h3>
      <p class="lead mb-4">{{ recipes.ingredients }}</p>
      <h3 class="h4 mb-3">Instructions</h3>
      <p class="lead">{{ recipes.instructions }}</p>
    </div>
  </div>
</div>

{% endblock %}{% block css %}
<link rel="stylesheet" href="{% static 'css/viewpage.css' %}" />
{% endblock %}